/*  Pokemon Champions Ability/Item lookup table
 *
 *  From: https://github.com/PokemonAutomation/
 *
 *  slug -> kind (ABILITY / ITEM / UNKNOWN). Backing table is generated by
 *  tools/generate_ability_item_table.py from PS data.
 */

#ifndef PokemonAutomation_PokemonChampions_AbilityItemTable_H
#define PokemonAutomation_PokemonChampions_AbilityItemTable_H

#include <string>
#include <cstddef>

namespace PokemonAutomation{
namespace NintendoSwitch{
namespace PokemonChampions{


enum class AbilityItemKind{
    UNKNOWN,
    ABILITY,
    ITEM,
};


//  Look up a slugified display name (e.g. "rough-skin", "leftovers") and
//  return whether it is an ability, item, or unknown.
AbilityItemKind lookup_ability_item_kind(const std::string& slug);


//  Fuzzy lookup: find the closest slug within `max_distance` Levenshtein
//  edits (default 1). On a match, returns its kind and writes the corrected
//  slug to *corrected_out. On no match, returns UNKNOWN and leaves
//  corrected_out untouched. Use after lookup_ability_item_kind misses to
//  recover from OCR misreads like "rough-skir" -> "rough-skin".
AbilityItemKind fuzzy_lookup_ability_item_kind(
    const std::string& slug,
    std::string* corrected_out,
    size_t max_distance = 1
);


size_t ability_item_table_size();


}}}
#endif
