//  Generated by tools/generate_battle_log_patterns.py — do not edit by hand.
//  Source: pokemon-showdown/data/text/default.ts

#include "PokemonChampions_BattleLogPatterns.h"

namespace PokemonAutomation{
namespace NintendoSwitch{
namespace PokemonChampions{

const std::vector<BattleLogPattern>& battle_log_patterns(){
    static const std::vector<BattleLogPattern> patterns = []{
        std::vector<BattleLogPattern> v;
        v.push_back({
            std::regex(R"___(It\ created\ a\ bizarre\ area\ in\ which\ Pokémon's\ held\ items\ lose\ their\ effects!?)___"),
            BattleLogEventType::FIELD_EFFECT,
            0,
            R"___(magic room)___",
            {},
            R"___(  It created a bizarre area in which Pokémon's held items lose their effects!)___",
            R"___(magicroom.start)___",
        });
        v.push_back({
            std::regex(R"___(It\ created\ a\ bizarre\ area\ in\ which\ Defense\ and\ Sp\.\ Def\ stats\ are\ swapped!?)___"),
            BattleLogEventType::FIELD_EFFECT,
            0,
            R"___(wonder room)___",
            {},
            R"___(  It created a bizarre area in which Defense and Sp. Def stats are swapped!)___",
            R"___(wonderroom.start)___",
        });
        v.push_back({
            std::regex(R"___(Wonder\ Room\ wore\ off,\ and\ Defense\ and\ Sp\.\ Def\ stats\ returned\ to\ normal!?)___"),
            BattleLogEventType::FIELD_EFFECT,
            0,
            R"___(wonder room)___",
            {},
            R"___(  Wonder Room wore off, and Defense and Sp. Def stats returned to normal!)___",
            R"___(wonderroom.end)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ switched\ all\ changes\ to\ its\ Defense\ and\ Sp\.\ Def\ with\ its\ target!?)___"),
            BattleLogEventType::STAT_CHANGE_OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] switched all changes to its Defense and Sp. Def with its target!)___",
            R"___(default.swapDefensiveBoost)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ switched\ all\ changes\ to\ its\ Attack\ and\ Sp\.\ Atk\ with\ its\ target!?)___"),
            BattleLogEventType::STAT_CHANGE_OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] switched all changes to its Attack and Sp. Atk with its target!)___",
            R"___(default.swapOffensiveBoost)___",
        });
        v.push_back({
            std::regex(R"___(Magic\ Room\ wore\ off,\ and\ held\ items'\ effects\ returned\ to\ normal!?)___"),
            BattleLogEventType::FIELD_EFFECT,
            0,
            R"___(magic room)___",
            {},
            R"___(  Magic Room wore off, and held items' effects returned to normal!)___",
            R"___(magicroom.end)___",
        });
        v.push_back({
            std::regex(R"___(Mysterious\ strong\ winds\ are\ protecting\ Flying\-type\ Pokémon!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  Mysterious strong winds are protecting Flying-type Pokémon!)___",
            R"___(deltastream.start)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ returned\ its\ decreased\ stats\ to\ normal\ using\ its\ Z\-Power!?)___"),
            BattleLogEventType::STAT_CHANGE_OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] returned its decreased stats to normal using its Z-Power!)___",
            R"___(default.clearBoostFromZEffect)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ shook\ its\ head\.\ It\ seems\ like\ it\ can't\ use\ this\ move\.\.\.?)___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] shook its head. It seems like it can't use this move...)___",
            R"___(dynamax.fail)___",
        });
        v.push_back({
            std::regex(R"___(The\ Water\-type\ attack\ evaporated\ in\ the\ harsh\ sunlight!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The Water-type attack evaporated in the harsh sunlight!)___",
            R"___(desolateland.blockMove)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ Primal\ Reversion!\ It\ reverted\ to\ its\ primal\ state!?)___"),
            BattleLogEventType::PRIMAL,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___([POKEMON]'s Primal Reversion! It reverted to its primal state!)___",
            R"___(default.primal)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ will\ restore\ its\ replacement's\ HP\ using\ its\ Z\-Power!?)___"),
            BattleLogEventType::HEAL,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] will restore its replacement's HP using its Z-Power!)___",
            R"___(healreplacement.activate)___",
        });
        v.push_back({
            std::regex(R"___(The\ extremely\ harsh\ sunlight\ was\ not\ lessened\ at\ all!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The extremely harsh sunlight was not lessened at all!)___",
            R"___(desolateland.block)___",
        });
        v.push_back({
            std::regex(R"___(The\ two\ moves\ have\ become\ one!\ It's\ a\ combined\ move!?)___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {},
            R"___(  The two moves have become one! It's a combined move!)___",
            R"___(default.combine)___",
        });
        v.push_back({
            std::regex(R"___(The\ Fire\-type\ attack\ fizzled\ out\ in\ the\ heavy\ rain!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The Fire-type attack fizzled out in the heavy rain!)___",
            R"___(primordialsea.blockMove)___",
        });
        v.push_back({
            std::regex(R"___(The\ electricity\ disappeared\ from\ the\ battlefield\.?)___"),
            BattleLogEventType::TERRAIN,
            0,
            R"___()___",
            {},
            R"___(  The electricity disappeared from the battlefield.)___",
            R"___(electricterrain.end)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ used\ (.+?)!\
\ \ But\ there\ was\ no\ PP\ left\ for\ the\ move!?)___"),
            BattleLogEventType::CANT,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::MOVE},
            R"___([POKEMON] used [MOVE]!
  But there was no PP left for the move!)___",
            R"___(nopp.cant)___",
        });
        v.push_back({
            std::regex(R"___(The\ mysterious\ strong\ winds\ weakened\ the\ attack!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The mysterious strong winds weakened the attack!)___",
            R"___(deltastream.activate)___",
        });
        v.push_back({
            std::regex(R"___(The\ mysterious\ strong\ winds\ blow\ on\ regardless!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The mysterious strong winds blow on regardless!)___",
            R"___(deltastream.block)___",
        });
        v.push_back({
            std::regex(R"___(An\ electric\ current\ ran\ across\ the\ battlefield!?)___"),
            BattleLogEventType::TERRAIN,
            0,
            R"___()___",
            {},
            R"___(  An electric current ran across the battlefield!)___",
            R"___(electricterrain.start)___",
        });
        v.push_back({
            std::regex(R"___(The\ weirdness\ disappeared\ from\ the\ battlefield!?)___"),
            BattleLogEventType::TERRAIN,
            0,
            R"___()___",
            {},
            R"___(  The weirdness disappeared from the battlefield!)___",
            R"___(psychicterrain.end)___",
        });
        v.push_back({
            std::regex(R"___(The\ move\ was\ blocked\ by\ the\ power\ of\ Dynamax!?)___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {},
            R"___(  The move was blocked by the power of Dynamax!)___",
            R"___(dynamax.block)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ couldn't\ fully\ protect\ itself\ and\ got\ hurt!?)___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] couldn't fully protect itself and got hurt!)___",
            R"___(default.zBroken)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ boosted\ its\ (.+?)\ drastically\ using\ its\ Z\-Power!?)___"),
            BattleLogEventType::STAT_CHANGE,
            3,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  [POKEMON] boosted its [STAT] drastically using its Z-Power!)___",
            R"___(default.boost3FromZEffect)___",
        });
        v.push_back({
            std::regex(R"___(The\ mysterious\ strong\ winds\ have\ dissipated!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The mysterious strong winds have dissipated!)___",
            R"___(deltastream.end)___",
        });
        v.push_back({
            std::regex(R"___(The\ grass\ disappeared\ from\ the\ battlefield\.?)___"),
            BattleLogEventType::TERRAIN,
            0,
            R"___()___",
            {},
            R"___(  The grass disappeared from the battlefield.)___",
            R"___(grassyterrain.end)___",
        });
        v.push_back({
            std::regex(R"___(The\ mist\ disappeared\ from\ the\ battlefield\.?)___"),
            BattleLogEventType::TERRAIN,
            0,
            R"___()___",
            {},
            R"___(  The mist disappeared from the battlefield.)___",
            R"___(mistyterrain.end)___",
        });
        v.push_back({
            std::regex(R"___(The\ twisted\ dimensions\ returned\ to\ normal!?)___"),
            BattleLogEventType::TRICK_ROOM,
            0,
            R"___()___",
            {},
            R"___(  The twisted dimensions returned to normal!)___",
            R"___(trickroom.end)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ surrounds\ itself\ with\ a\ protective\ mist!?)___"),
            BattleLogEventType::TERRAIN,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] surrounds itself with a protective mist!)___",
            R"___(mistyterrain.block)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ boosted\ its\ (.+?)\ sharply\ using\ its\ Z\-Power!?)___"),
            BattleLogEventType::STAT_CHANGE,
            2,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  [POKEMON] boosted its [STAT] sharply using its Z-Power!)___",
            R"___(default.boost2FromZEffect)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ paralyzed!\ It\ may\ be\ unable\ to\ move!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(paralyzed)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] is paralyzed! It may be unable to move!)___",
            R"___(par.start)___",
        });
        v.push_back({
            std::regex(R"___(There\ is\ no\ relief\ from\ this\ heavy\ rain!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  There is no relief from this heavy rain!)___",
            R"___(primordialsea.block)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ switched\ stat\ changes\ with\ its\ target!?)___"),
            BattleLogEventType::STAT_CHANGE_OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] switched stat changes with its target!)___",
            R"___(default.swapBoost)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ protected\ by\ the\ Electric\ Terrain!?)___"),
            BattleLogEventType::TERRAIN,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] is protected by the Electric Terrain!)___",
            R"___(electricterrain.block)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ fell\ from\ the\ sky\ due\ to\ the\ gravity!?)___"),
            BattleLogEventType::FIELD_EFFECT,
            0,
            R"___(gravity)___",
            {BattleLogSlot::POKEMON},
            R"___([POKEMON] fell from the sky due to the gravity!)___",
            R"___(gravity.activate)___",
        });
        v.push_back({
            std::regex(R"___(The\ effects\ of\ Water\ Sport\ have\ faded\.?)___"),
            BattleLogEventType::FIELD_EFFECT,
            0,
            R"___(water sport)___",
            {},
            R"___(  The effects of Water Sport have faded.)___",
            R"___(watersport.end)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ boosted\ its\ stats\ using\ its\ Z\-Power!?)___"),
            BattleLogEventType::STAT_CHANGE_OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] boosted its stats using its Z-Power!)___",
            R"___(default.boostMultipleFromZEffect)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ protected\ by\ the\ Psychic\ Terrain!?)___"),
            BattleLogEventType::TERRAIN,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] is protected by the Psychic Terrain!)___",
            R"___(psychicterrain.block)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ is\ reacting\ to\ (.+?)'s\ Mega\ Bracelet!?)___"),
            BattleLogEventType::MEGA_EVOLVE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM, BattleLogSlot::NONE},
            R"___(  [POKEMON]'s [ITEM] is reacting to [TRAINER]'s Mega Bracelet!)___",
            R"___(default.megaGen6)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ surrounded\ itself\ with\ its\ Z\-Power!?)___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] surrounded itself with its Z-Power!)___",
            R"___(default.zPower)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ snapped\ it\ out\ of\ its\ confusion!?)___"),
            BattleLogEventType::CONFUSION,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON]'s [ITEM] snapped it out of its confusion!)___",
            R"___(confusion.endFromItem)___",
        });
        v.push_back({
            std::regex(R"___(The\ sunlight\ turned\ extremely\ harsh!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The sunlight turned extremely harsh!)___",
            R"___(desolateland.start)___",
        });
        v.push_back({
            std::regex(R"___(Grass\ grew\ to\ cover\ the\ battlefield!?)___"),
            BattleLogEventType::TERRAIN,
            0,
            R"___()___",
            {},
            R"___(  Grass grew to cover the battlefield!)___",
            R"___(grassyterrain.start)___",
        });
        v.push_back({
            std::regex(R"___(Mist\ swirled\ around\ the\ battlefield!?)___"),
            BattleLogEventType::TERRAIN,
            0,
            R"___()___",
            {},
            R"___(  Mist swirled around the battlefield!)___",
            R"___(mistyterrain.start)___",
        });
        v.push_back({
            std::regex(R"___(The\ effects\ of\ Mud\ Sport\ have\ faded\.?)___"),
            BattleLogEventType::FIELD_EFFECT,
            0,
            R"___(mud sport)___",
            {},
            R"___(  The effects of Mud Sport have faded.)___",
            R"___(mudsport.end)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ restored\ its\ HP\ using\ its\ Z\-Power!?)___"),
            BattleLogEventType::HEAL,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] restored its HP using its Z-Power!)___",
            R"___(default.healFromZEffect)___",
        });
        v.push_back({
            std::regex(R"___(The\ extremely\ harsh\ sunlight\ faded\.?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The extremely harsh sunlight faded.)___",
            R"___(desolateland.end)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ has\ Terastallized\ into\ the\ (.+?)\-type!?)___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::EFFECT},
            R"___(  [POKEMON] has Terastallized into the [TYPE]-type!)___",
            R"___(default.terastallize)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ unleashes\ its\ full\-force\ Z\-Move!?)___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] unleashes its full-force Z-Move!)___",
            R"___(default.zEffect)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ is\ reacting\ to\ the\ Key\ Stone!?)___"),
            BattleLogEventType::MEGA_EVOLVE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON]'s [ITEM] is reacting to the Key Stone!)___",
            R"___(default.mega)___",
        });
        v.push_back({
            std::regex(R"___(All\ stat\ changes\ were\ eliminated!?)___"),
            BattleLogEventType::STAT_CHANGE_OTHER,
            0,
            R"___()___",
            {},
            R"___(  All stat changes were eliminated!)___",
            R"___(default.clearAllBoost)___",
        });
        v.push_back({
            std::regex(R"___(Electricity's\ power\ was\ weakened!?)___"),
            BattleLogEventType::FIELD_EFFECT,
            0,
            R"___(mud sport)___",
            {},
            R"___(  Electricity's power was weakened!)___",
            R"___(mudsport.start)___",
        });
        v.push_back({
            std::regex(R"___(Dynamax\ Energy\ gathered\ around\ (.+?)!?)___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {BattleLogSlot::NONE},
            R"___(  Dynamax Energy gathered around [TRAINER]!)___",
            R"___(default.canDynamaxOwn)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ boosted\ its\ (.+?)\ using\ its\ Z\-Power!?)___"),
            BattleLogEventType::STAT_CHANGE,
            1,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  [POKEMON] boosted its [STAT] using its Z-Power!)___",
            R"___(default.boostFromZEffect)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ became\ confused\ due\ to\ fatigue!?)___"),
            BattleLogEventType::CONFUSION,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] became confused due to fatigue!)___",
            R"___(confusion.startFromFatigue)___",
        });
        v.push_back({
            std::regex(R"___(It\ hurt\ itself\ in\ its\ confusion!?)___"),
            BattleLogEventType::DAMAGE,
            0,
            R"___()___",
            {},
            R"___(It hurt itself in its confusion!)___",
            R"___(confusion.damage)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ can't\ use\ (.+?)\ because\ of\ gravity!?)___"),
            BattleLogEventType::CANT,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::MOVE},
            R"___([POKEMON] can't use [MOVE] because of gravity!)___",
            R"___(gravity.cant)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ stat\ changes\ were\ inverted!?)___"),
            BattleLogEventType::STAT_CHANGE_OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON]'s stat changes were inverted!)___",
            R"___(default.invertBoost)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ snapped\ out\ of\ its\ confusion!?)___"),
            BattleLogEventType::CONFUSION,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] snapped out of its confusion!)___",
            R"___(confusion.end)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ buffeted\ by\ the\ sandstorm!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] is buffeted by the sandstorm!)___",
            R"___(sandstorm.damage)___",
        });
        v.push_back({
            std::regex(R"___(Battle\ started\ between\ (.+?)\ and\ (.+?)!?)___"),
            BattleLogEventType::BATTLE_START,
            0,
            R"___()___",
            {BattleLogSlot::NONE, BattleLogSlot::NONE},
            R"___(Battle started between [TRAINER] and [TRAINER]!)___",
            R"___(default.startBattle)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ reacting\ to\ (.+?)'s\ Key\ Stone!?)___"),
            BattleLogEventType::MEGA_EVOLVE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::NONE},
            R"___(  [POKEMON] is reacting to [TRAINER]'s Key Stone!)___",
            R"___(default.megaNoItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ has\ Mega\ Evolved\ into\ Mega\ (.+?)!?)___"),
            BattleLogEventType::MEGA_EVOLVE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::EFFECT},
            R"___([POKEMON] has Mega Evolved into Mega [SPECIES]!)___",
            R"___(default.transformMega)___",
        });
        v.push_back({
            std::regex(R"___(The\ (.+?)\ weakened\ the\ damage\ to\ (.+?)!?)___"),
            BattleLogEventType::ITEM_ACTIVATED,
            0,
            R"___()___",
            {BattleLogSlot::ITEM, BattleLogSlot::POKEMON},
            R"___(  The [ITEM] weakened the damage to [POKEMON]!)___",
            R"___(default.activateWeaken)___",
        });
        v.push_back({
            std::regex(R"___(The\ (.+?)\ drastically\ lowered\ (.+?)'s\ (.+?)!?)___"),
            BattleLogEventType::STAT_CHANGE,
            -3,
            R"___()___",
            {BattleLogSlot::ITEM, BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  The [ITEM] drastically lowered [POKEMON]'s [STAT]!)___",
            R"___(default.unboost3FromItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ stat\ changes\ were\ removed!?)___"),
            BattleLogEventType::STAT_CHANGE_OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON]'s stat changes were removed!)___",
            R"___(default.clearBoost)___",
        });
        v.push_back({
            std::regex(R"___(It's\ extremely\ effective\ on\ (.+?)!?)___"),
            BattleLogEventType::SUPER_EFFECTIVE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  It's extremely effective on [POKEMON]!)___",
            R"___(default.extremelyEffectiveSpread)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ paralyzed!\ It\ can't\ move!?)___"),
            BattleLogEventType::CANT,
            0,
            R"___(paralyzed)___",
            {BattleLogSlot::POKEMON},
            R"___([POKEMON] is paralyzed! It can't move!)___",
            R"___(par.cant)___",
        });
        v.push_back({
            std::regex(R"___(The\ (.+?)\ drastically\ raised\ (.+?)'s\ (.+?)!?)___"),
            BattleLogEventType::STAT_CHANGE,
            3,
            R"___()___",
            {BattleLogSlot::ITEM, BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  The [ITEM] drastically raised [POKEMON]'s [STAT]!)___",
            R"___(default.boost3FromItem)___",
        });
        v.push_back({
            std::regex(R"___(It's\ not\ very\ effective\ on\ (.+?)\.?)___"),
            BattleLogEventType::NOT_EFFECTIVE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  It's not very effective on [POKEMON].)___",
            R"___(default.resistedSpread)___",
        });
        v.push_back({
            std::regex(R"___(It's\ mostly\ ineffective\ on\ (.+?)\.?)___"),
            BattleLogEventType::NOT_EFFECTIVE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  It's mostly ineffective on [POKEMON].)___",
            R"___(default.mostlyIneffectiveSpread)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ cured\ of\ its\ poisoning!?)___"),
            BattleLogEventType::STATUS_HEALED,
            0,
            R"___(poisoned)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] was cured of its poisoning!)___",
            R"___(psn.end)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ badly\ poisoned\ by\ the\ (.+?)!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(badly poisoned)___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON] was badly poisoned by the [ITEM]!)___",
            R"___(tox.startFromItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ flinched\ and\ couldn't\ move!?)___"),
            BattleLogEventType::CANT,
            0,
            R"___(flinched)___",
            {BattleLogSlot::POKEMON},
            R"___([POKEMON] flinched and couldn't move!)___",
            R"___(flinch.cant)___",
        });
        v.push_back({
            std::regex(R"___(The\ (.+?)\ strengthened\ (.+?)'s\ power!?)___"),
            BattleLogEventType::ITEM_ACTIVATED,
            0,
            R"___()___",
            {BattleLogSlot::ITEM, BattleLogSlot::POKEMON},
            R"___(  The [ITEM] strengthened [POKEMON]'s power!)___",
            R"___(default.useGem)___",
        });
        v.push_back({
            std::regex(R"___(The\ Pokémon\ was\ hit\ (.+?)\ times!?)___"),
            BattleLogEventType::HIT_COUNT,
            0,
            R"___()___",
            {BattleLogSlot::EFFECT},
            R"___(  The Pokémon was hit [NUMBER] times!)___",
            R"___(default.hitCount)___",
        });
        v.push_back({
            std::regex(R"___(The\ Pokémon\ was\ hit\ 1\ time!?)___"),
            BattleLogEventType::HIT_COUNT,
            0,
            R"___()___",
            {},
            R"___(  The Pokémon was hit 1 time!)___",
            R"___(default.hitCountSingular)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ damaged\ by\ the\ recoil!?)___"),
            BattleLogEventType::DAMAGE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] was damaged by the recoil!)___",
            R"___(recoil.damage)___",
        });
        v.push_back({
            std::regex(R"___(A\ heavy\ rain\ began\ to\ fall!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  A heavy rain began to fall!)___",
            R"___(primordialsea.start)___",
        });
        v.push_back({
            std::regex(R"___(Gravity\ returned\ to\ normal!?)___"),
            BattleLogEventType::FIELD_EFFECT,
            0,
            R"___(gravity)___",
            {},
            R"___(  Gravity returned to normal!)___",
            R"___(gravity.end)___",
        });
        v.push_back({
            std::regex(R"___(It's\ not\ very\ effective\.\.\.?)___"),
            BattleLogEventType::NOT_EFFECTIVE,
            0,
            R"___()___",
            {},
            R"___(  It's not very effective...)___",
            R"___(default.resisted)___",
        });
        v.push_back({
            std::regex(R"___(It's\ mostly\ ineffective\.\.\.?)___"),
            BattleLogEventType::NOT_EFFECTIVE,
            0,
            R"___()___",
            {},
            R"___(  It's mostly ineffective...)___",
            R"___(default.mostlyIneffective)___",
        });
        v.push_back({
            std::regex(R"___(But\ there\ was\ no\ target\.\.\.?)___"),
            BattleLogEventType::FAILED,
            0,
            R"___()___",
            {},
            R"___(  But there was no target...)___",
            R"___(default.noTarget)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ slept\ and\ became\ healthy!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(asleep)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] slept and became healthy!)___",
            R"___(slp.startFromRest)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ stats\ were\ not\ lowered!?)___"),
            BattleLogEventType::STAT_CHANGE_OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON]'s stats were not lowered!)___",
            R"___(unboost.fail)___",
        });
        v.push_back({
            std::regex(R"___(The\ sunlight\ turned\ harsh!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The sunlight turned harsh!)___",
            R"___(sunnyday.start)___",
        });
        v.push_back({
            std::regex(R"___(The\ hail\ is\ crashing\ down\.?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  (The hail is crashing down.))___",
            R"___(hail.upkeep)___",
        });
        v.push_back({
            std::regex(R"___(The\ heavy\ rain\ has\ lifted!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The heavy rain has lifted!)___",
            R"___(primordialsea.end)___",
        });
        v.push_back({
            std::regex(R"___(The\ battlefield\ got\ weird!?)___"),
            BattleLogEventType::TERRAIN,
            0,
            R"___()___",
            {},
            R"___(  The battlefield got weird!)___",
            R"___(psychicterrain.start)___",
        });
        v.push_back({
            std::regex(R"___(Fire's\ power\ was\ weakened!?)___"),
            BattleLogEventType::FIELD_EFFECT,
            0,
            R"___(water sport)___",
            {},
            R"___(  Fire's power was weakened!)___",
            R"___(watersport.start)___",
        });
        v.push_back({
            std::regex(R"___(The\ (.+?)\ weakened\ damage\ to\ (.+?)!?)___"),
            BattleLogEventType::ITEM_ACTIVATED,
            0,
            R"___()___",
            {BattleLogSlot::ITEM, BattleLogSlot::POKEMON},
            R"___(  The [ITEM] weakened damage to [POKEMON]!)___",
            R"___(default.eatItemWeaken)___",
        });
        v.push_back({
            std::regex(R"___(The\ (.+?)\ harshly\ lowered\ (.+?)'s\ (.+?)!?)___"),
            BattleLogEventType::STAT_CHANGE,
            -2,
            R"___()___",
            {BattleLogSlot::ITEM, BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  The [ITEM] harshly lowered [POKEMON]'s [STAT]!)___",
            R"___(default.unboost2FromItem)___",
        });
        v.push_back({
            std::regex(R"___(It's\ super\ effective\ on\ (.+?)!?)___"),
            BattleLogEventType::SUPER_EFFECTIVE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  It's super effective on [POKEMON]!)___",
            R"___(default.superEffectiveSpread)___",
        });
        v.push_back({
            std::regex(R"___(It's\ extremely\ effective!?)___"),
            BattleLogEventType::SUPER_EFFECTIVE,
            0,
            R"___()___",
            {},
            R"___(  It's extremely effective!)___",
            R"___(default.extremelyEffective)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ already\ frozen\ solid!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(frozen)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] is already frozen solid!)___",
            R"___(frz.alreadyStarted)___",
        });
        v.push_back({
            std::regex(R"___(The\ harsh\ sunlight\ faded\.?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The harsh sunlight faded.)___",
            R"___(sunnyday.end)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ buffeted\ by\ the\ hail!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] is buffeted by the hail!)___",
            R"___(hail.damage)___",
        });
        v.push_back({
            std::regex(R"___(The\ snow\ is\ falling\ down\.?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  (The snow is falling down.))___",
            R"___(snowscape.upkeep)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ restored\ HP\ using\ its\ (.+?)!?)___"),
            BattleLogEventType::HEAL,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::EFFECT},
            R"___(  [POKEMON] restored HP using its [EFFECT]!)___",
            R"___(default.healFromEffect)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ won't\ go\ any\ higher!?)___"),
            BattleLogEventType::STAT_CHANGE_AT_CAP,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  [POKEMON]'s [STAT] won't go any higher!)___",
            R"___(default.boost0)___",
        });
        v.push_back({
            std::regex(R"___(The\ (.+?)\ sharply\ raised\ (.+?)'s\ (.+?)!?)___"),
            BattleLogEventType::STAT_CHANGE,
            2,
            R"___()___",
            {BattleLogSlot::ITEM, BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  The [ITEM] sharply raised [POKEMON]'s [STAT]!)___",
            R"___(default.boost2FromItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ copied\ (.+?)'s\ stat\ changes!?)___"),
            BattleLogEventType::STAT_CHANGE_OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::POKEMON},
            R"___(  [POKEMON] copied [TARGET]'s stat changes!)___",
            R"___(default.copyBoost)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ cured\ of\ paralysis!?)___"),
            BattleLogEventType::STATUS_HEALED,
            0,
            R"___(paralyzed)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] was cured of paralysis!)___",
            R"___(par.end)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ cured\ its\ paralysis!?)___"),
            BattleLogEventType::STATUS_HEALED,
            0,
            R"___(paralyzed)___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON]'s [ITEM] cured its paralysis!)___",
            R"___(par.endFromItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ had\ its\ energy\ drained!?)___"),
            BattleLogEventType::HEAL,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [SOURCE] had its energy drained!)___",
            R"___(drain.heal)___",
        });
        v.push_back({
            std::regex(R"___(The\ sandstorm\ is\ raging\.?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  (The sandstorm is raging.))___",
            R"___(sandstorm.upkeep)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ twisted\ the\ dimensions!?)___"),
            BattleLogEventType::TRICK_ROOM,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] twisted the dimensions!)___",
            R"___(trickroom.start)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ kept\ going\ and\ crashed!?)___"),
            BattleLogEventType::DAMAGE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] kept going and crashed!)___",
            R"___(crash.damage)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ won't\ go\ any\ lower!?)___"),
            BattleLogEventType::STAT_CHANGE_AT_CAP,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  [POKEMON]'s [STAT] won't go any lower!)___",
            R"___(default.unboost0)___",
        });
        v.push_back({
            std::regex(R"___(The\ sandstorm\ subsided\.?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The sandstorm subsided.)___",
            R"___(sandstorm.end)___",
        });
        v.push_back({
            std::regex(R"___(The\ sunlight\ is\ strong\.?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  (The sunlight is strong.))___",
            R"___(sunnyday.upkeep)___",
        });
        v.push_back({
            std::regex(R"___(Rain\ continues\ to\ fall\.?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  (Rain continues to fall.))___",
            R"___(raindance.upkeep)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ and\ (.+?)\ switched\ places!?)___"),
            BattleLogEventType::SWITCH_OUT,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::POKEMON},
            R"___([POKEMON] and [TARGET] switched places!)___",
            R"___(default.swap)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ made\ it\ the\ (.+?)\ type!?)___"),
            BattleLogEventType::TYPE_CHANGE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::EFFECT, BattleLogSlot::EFFECT},
            R"___(  [POKEMON]'s [EFFECT] made it the [TYPE] type!)___",
            R"___(default.typeChangeFromEffect)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ hurt\ by\ its\ burn!?)___"),
            BattleLogEventType::STATUS_DAMAGE,
            0,
            R"___(burned)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] was hurt by its burn!)___",
            R"___(brn.damage)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ already\ paralyzed!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(paralyzed)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] is already paralyzed!)___",
            R"___(par.alreadyStarted)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ can\ no\ longer\ escape!?)___"),
            BattleLogEventType::EFFECT_START,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] can no longer escape!)___",
            R"___(trapped.start)___",
        });
        v.push_back({
            std::regex(R"___(A\ sandstorm\ kicked\ up!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  A sandstorm kicked up!)___",
            R"___(sandstorm.start)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ moved\ to\ the\ center!?)___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___([POKEMON] moved to the center!)___",
            R"___(default.swapCenter)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ lost\ (.+?)\ of\ its\ health!?)___"),
            BattleLogEventType::DAMAGE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::EFFECT},
            R"___(  ([POKEMON] lost [PERCENTAGE] of its health!))___",
            R"___(default.damagePercentage)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ had\ its\ HP\ restored\.?)___"),
            BattleLogEventType::HEAL,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] had its HP restored.)___",
            R"___(default.heal)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ rose\ drastically!?)___"),
            BattleLogEventType::STAT_CHANGE,
            3,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  [POKEMON]'s [STAT] rose drastically!)___",
            R"___(default.boost3)___",
        });
        v.push_back({
            std::regex(R"___(It's\ super\ effective!?)___"),
            BattleLogEventType::SUPER_EFFECTIVE,
            0,
            R"___()___",
            {},
            R"___(  It's super effective!)___",
            R"___(default.superEffective)___",
        });
        v.push_back({
            std::regex(R"___(It\ doesn't\ affect\ (.+?)\.\.\.?)___"),
            BattleLogEventType::IMMUNE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  It doesn't affect [POKEMON]...)___",
            R"___(default.immune)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ already\ poisoned!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(poisoned)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] is already poisoned!)___",
            R"___(psn.alreadyStarted)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ cured\ its\ poison!?)___"),
            BattleLogEventType::STATUS_HEALED,
            0,
            R"___(poisoned)___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON]'s [ITEM] cured its poison!)___",
            R"___(psn.endFromItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ already\ confused!?)___"),
            BattleLogEventType::CONFUSION,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] is already confused!)___",
            R"___(confusion.alreadyStarted)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ type\ changed\ to\ (.+?)!?)___"),
            BattleLogEventType::TYPE_CHANGE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::EFFECT},
            R"___(  [POKEMON]'s type changed to [TYPE]!)___",
            R"___(default.typeChange)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ type\ was\ added\ to\ (.+?)!?)___"),
            BattleLogEventType::TYPE_CHANGE,
            0,
            R"___()___",
            {BattleLogSlot::EFFECT, BattleLogSlot::POKEMON},
            R"___(  [TYPE] type was added to [POKEMON]!)___",
            R"___(default.typeAdd)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ avoided\ the\ attack!?)___"),
            BattleLogEventType::MISS,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] avoided the attack!)___",
            R"___(default.miss)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ burned\ by\ the\ (.+?)!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(burned)___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON] was burned by the [ITEM]!)___",
            R"___(brn.startFromItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ healed\ its\ burn!?)___"),
            BattleLogEventType::STATUS_HEALED,
            0,
            R"___(burned)___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON]'s [ITEM] healed its burn!)___",
            R"___(brn.endFromItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ hurt\ by\ poison!?)___"),
            BattleLogEventType::STATUS_DAMAGE,
            0,
            R"___(poisoned)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] was hurt by poison!)___",
            R"___(psn.damage)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ badly\ poisoned!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(badly poisoned)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] was badly poisoned!)___",
            R"___(tox.start)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ was\ not\ lowered!?)___"),
            BattleLogEventType::STAT_CHANGE_OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  [POKEMON]'s [STAT] was not lowered!)___",
            R"___(unboost.failSingular)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ returned\ to\ normal!?)___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  ([POKEMON] returned to normal!))___",
            R"___(dynamax.end)___",
        });
        v.push_back({
            std::regex(R"___(Gravity\ intensified!?)___"),
            BattleLogEventType::FIELD_EFFECT,
            0,
            R"___(gravity)___",
            {},
            R"___(  Gravity intensified!)___",
            R"___(gravity.start)___",
        });
        v.push_back({
            std::regex(R"___(A\ critical\ hit\ on\ (.+?)!?)___"),
            BattleLogEventType::CRIT,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  A critical hit on [POKEMON]!)___",
            R"___(default.critSpread)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ already\ burned!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(burned)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] is already burned!)___",
            R"___(brn.alreadyStarted)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ burn\ was\ healed!?)___"),
            BattleLogEventType::STATUS_HEALED,
            0,
            R"___(burned)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON]'s burn was healed!)___",
            R"___(brn.end)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ melted\ the\ ice!?)___"),
            BattleLogEventType::STATUS_HEALED,
            0,
            R"___(frozen)___",
            {BattleLogSlot::POKEMON, BattleLogSlot::MOVE},
            R"___(  [POKEMON]'s [MOVE] melted the ice!)___",
            R"___(frz.endFromMove)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ already\ asleep!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(asleep)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] is already asleep!)___",
            R"___(slp.alreadyStarted)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ has\ no\ moves\ left!?)___"),
            BattleLogEventType::CANT,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] has no moves left!)___",
            R"___(struggle.activate)___",
        });
        v.push_back({
            std::regex(R"___(It\ started\ to\ rain!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  It started to rain!)___",
            R"___(raindance.start)___",
        });
        v.push_back({
            std::regex(R"___(It\ started\ to\ hail!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  It started to hail!)___",
            R"___(hail.start)___",
        });
        v.push_back({
            std::regex(R"___(It\ started\ to\ snow!?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  It started to snow!)___",
            R"___(snowscape.start)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ HP\ was\ restored\.?)___"),
            BattleLogEventType::TERRAIN,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON]'s HP was restored.)___",
            R"___(grassyterrain.heal)___",
        });
        v.push_back({
            std::regex(R"___(Tie\ between\ (.+?)\ and\ (.+?)!?)___"),
            BattleLogEventType::BATTLE_END,
            0,
            R"___()___",
            {BattleLogSlot::NONE, BattleLogSlot::NONE},
            R"___(Tie between [TRAINER] and [TRAINER]!)___",
            R"___(default.tieBattle)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ hurt\ by\ its\ (.+?)!?)___"),
            BattleLogEventType::DAMAGE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON] was hurt by its [ITEM]!)___",
            R"___(default.damageFromItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ fell\ severely!?)___"),
            BattleLogEventType::STAT_CHANGE,
            -3,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  [POKEMON]'s [STAT] fell severely!)___",
            R"___(default.unboost3)___",
        });
        v.push_back({
            std::regex(R"___(It's\ a\ one\-hit\ KO!?)___"),
            BattleLogEventType::OHKO,
            0,
            R"___()___",
            {},
            R"___(  It's a one-hit KO!)___",
            R"___(default.ohko)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ frozen\ solid!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(frozen)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] was frozen solid!)___",
            R"___(frz.start)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ dragged\ out!?)___"),
            BattleLogEventType::DRAG,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___([FULLNAME] was dragged out!)___",
            R"___(default.drag)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ can\ dynamax\ now!?)___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {BattleLogSlot::NONE},
            R"___(  [TRAINER] can dynamax now!)___",
            R"___(default.canDynamax)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ freed\ from\ (.+?)!?)___"),
            BattleLogEventType::EFFECT_END,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::EFFECT},
            R"___(  [POKEMON] was freed from [EFFECT]!)___",
            R"___(default.end)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ hurt\ by\ (.+?)'s\ (.+?)!?)___"),
            BattleLogEventType::DAMAGE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON] was hurt by [SOURCE]'s [ITEM]!)___",
            R"___(default.damageFromPokemon)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ rose\ sharply!?)___"),
            BattleLogEventType::STAT_CHANGE,
            2,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  [POKEMON]'s [STAT] rose sharply!)___",
            R"___(default.boost2)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ fell\ harshly!?)___"),
            BattleLogEventType::STAT_CHANGE,
            -2,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  [POKEMON]'s [STAT] fell harshly!)___",
            R"___(default.unboost2)___",
        });
        v.push_back({
            std::regex(R"___(The\ (.+?)\ lowered\ (.+?)'s\ (.+?)!?)___"),
            BattleLogEventType::STAT_CHANGE,
            -1,
            R"___()___",
            {BattleLogSlot::ITEM, BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  The [ITEM] lowered [POKEMON]'s [STAT]!)___",
            R"___(default.unboostFromItem)___",
        });
        v.push_back({
            std::regex(R"___(It\ had\ no\ effect!?)___"),
            BattleLogEventType::IMMUNE,
            0,
            R"___()___",
            {},
            R"___(  It had no effect!)___",
            R"___(default.immuneNoPokemon)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ attack\ missed!?)___"),
            BattleLogEventType::MISS,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [SOURCE]'s attack missed!)___",
            R"___(default.missNoPokemon)___",
        });
        v.push_back({
            std::regex(R"___(Automatic\ center!?)___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {},
            R"___(  Automatic center!)___",
            R"___(default.center)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ defrosted\ it!?)___"),
            BattleLogEventType::STATUS_HEALED,
            0,
            R"___(frozen)___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON]'s [ITEM] defrosted it!)___",
            R"___(frz.endFromItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ frozen\ solid!?)___"),
            BattleLogEventType::CANT,
            0,
            R"___(frozen)___",
            {BattleLogSlot::POKEMON},
            R"___([POKEMON] is frozen solid!)___",
            R"___(frz.cant)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ became\ confused!?)___"),
            BattleLogEventType::CONFUSION,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] became confused!)___",
            R"___(confusion.start)___",
        });
        v.push_back({
            std::regex(R"___(The\ rain\ stopped\.?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The rain stopped.)___",
            R"___(raindance.end)___",
        });
        v.push_back({
            std::regex(R"___(The\ hail\ stopped\.?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The hail stopped.)___",
            R"___(hail.end)___",
        });
        v.push_back({
            std::regex(R"___(The\ snow\ stopped\.?)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(  The snow stopped.)___",
            R"___(snowscape.end)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ won\ the\ battle!?)___"),
            BattleLogEventType::BATTLE_END,
            0,
            R"___()___",
            {BattleLogSlot::NONE},
            R"___(**[TRAINER]** won the battle!)___",
            R"___(default.winBattle)___",
        });
        v.push_back({
            std::regex(R"___(The\ (.+?)\ raised\ (.+?)'s\ (.+?)!?)___"),
            BattleLogEventType::STAT_CHANGE,
            1,
            R"___()___",
            {BattleLogSlot::ITEM, BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  The [ITEM] raised [POKEMON]'s [STAT]!)___",
            R"___(default.boostFromItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ fast\ asleep\.?)___"),
            BattleLogEventType::CANT,
            0,
            R"___(asleep)___",
            {BattleLogSlot::POKEMON},
            R"___([POKEMON] is fast asleep.)___",
            R"___(slp.cant)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ obtained\ one\ (.+?)\.?)___"),
            BattleLogEventType::ITEM_TRANSFER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON] obtained one [ITEM].)___",
            R"___(default.addItem)___",
        });
        v.push_back({
            std::regex(R"___(A\ critical\ hit!?)___"),
            BattleLogEventType::CRIT,
            0,
            R"___()___",
            {},
            R"___(  A critical hit!)___",
            R"___(default.crit)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ unaffected!?)___"),
            BattleLogEventType::IMMUNE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] is unaffected!)___",
            R"___(default.immuneOHKO)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ woke\ it\ up!?)___"),
            BattleLogEventType::STATUS_HEALED,
            0,
            R"___(asleep)___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON]'s [ITEM] woke it up!)___",
            R"___(slp.endFromItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ must\ recharge!?)___"),
            BattleLogEventType::CANT,
            0,
            R"___(recharging)___",
            {BattleLogSlot::POKEMON},
            R"___([POKEMON] must recharge!)___",
            R"___(recharge.cant)___",
        });
        v.push_back({
            std::regex(R"___(But\ it\ failed!?)___"),
            BattleLogEventType::FAILED,
            0,
            R"___()___",
            {},
            R"___(  But it failed!)___",
            R"___(default.fail)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ poisoned!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(poisoned)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] was poisoned!)___",
            R"___(psn.start)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ HP\ is\ full!?)___"),
            BattleLogEventType::FAILED,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON]'s HP is full!)___",
            R"___(heal.fail)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ transformed!?)___"),
            BattleLogEventType::TRANSFORM,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___([POKEMON] transformed!)___",
            R"___(default.transform)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ started\ on\ (.+?)!?)___"),
            BattleLogEventType::EFFECT_START,
            0,
            R"___()___",
            {BattleLogSlot::EFFECT, BattleLogSlot::POKEMON},
            R"___(  ([EFFECT] started on [POKEMON]!))___",
            R"___(default.start)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ started\ on\ (.+?)!?)___"),
            BattleLogEventType::EFFECT_START,
            0,
            R"___()___",
            {BattleLogSlot::EFFECT, BattleLogSlot::NONE},
            R"___(  ([EFFECT] started on [TEAM]!))___",
            R"___(default.startTeamEffect)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ hurt\ by\ (.+?)!?)___"),
            BattleLogEventType::DAMAGE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::MOVE},
            R"___(  [POKEMON] is hurt by [MOVE]!)___",
            R"___(default.damageFromPartialTrapping)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ fell\ asleep!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(asleep)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] fell asleep!)___",
            R"___(slp.start)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ is\ confused!?)___"),
            BattleLogEventType::CONFUSION,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] is confused!)___",
            R"___(confusion.activate)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ grew\ drowsy!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(drowsy)___",
            {BattleLogSlot::POKEMON},
            R"___([POKEMON] grew drowsy!)___",
            R"___(yawn.start)___",
        });
        v.push_back({
            std::regex(R"___((.+?),\ come\ back!?)___"),
            BattleLogEventType::SWITCH_OUT,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___([NICKNAME], come back!)___",
            R"___(default.switchOutOwn)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ can't\ use\ (.+?)!?)___"),
            BattleLogEventType::CANT,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::MOVE},
            R"___([POKEMON] can't use [MOVE]!)___",
            R"___(default.cant)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ can't\ move!?)___"),
            BattleLogEventType::CANT,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___([POKEMON] can't move!)___",
            R"___(default.cantNoMove)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ burned!?)___"),
            BattleLogEventType::STATUS_INFLICTED,
            0,
            R"___(burned)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] was burned!)___",
            R"___(brn.start)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ thawed\ out!?)___"),
            BattleLogEventType::STATUS_HEALED,
            0,
            R"___(frozen)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] thawed out!)___",
            R"___(frz.end)___",
        });
        v.push_back({
            std::regex(R"___(Strong\ Winds)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(Strong Winds)___",
            R"___(deltastream.weatherName)___",
        });
        v.push_back({
            std::regex(R"___(==\ Turn\ (.+?)\ ==)___"),
            BattleLogEventType::TURN_MARKER,
            0,
            R"___()___",
            {BattleLogSlot::EFFECT},
            R"___(== Turn [NUMBER] ==)___",
            R"___(default.turn)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ sent\ out\ (.+?)!?)___"),
            BattleLogEventType::SWITCH_IN,
            0,
            R"___()___",
            {BattleLogSlot::NONE, BattleLogSlot::POKEMON},
            R"___([TRAINER] sent out [FULLNAME]!)___",
            R"___(default.switchIn)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ withdrew\ (.+?)!?)___"),
            BattleLogEventType::SWITCH_OUT,
            0,
            R"___()___",
            {BattleLogSlot::NONE, BattleLogSlot::POKEMON},
            R"___([TRAINER] withdrew [NICKNAME]!)___",
            R"___(default.switchOut)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ activated!?)___"),
            BattleLogEventType::EFFECT_ACTIVATE,
            0,
            R"___()___",
            {BattleLogSlot::EFFECT},
            R"___(  ([EFFECT] activated!))___",
            R"___(default.activate)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ ended\ on\ (.+?)!?)___"),
            BattleLogEventType::EFFECT_END,
            0,
            R"___()___",
            {BattleLogSlot::EFFECT, BattleLogSlot::NONE},
            R"___(  ([EFFECT] ended on [TEAM]!))___",
            R"___(default.endTeamEffect)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ acquired\ (.+?)!?)___"),
            BattleLogEventType::ABILITY_CHANGE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ABILITY},
            R"___(  [POKEMON] acquired [ABILITY]!)___",
            R"___(default.changeAbility)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ stole\ (.+?)'s\ (.+?)!?)___"),
            BattleLogEventType::ITEM_TRANSFER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON] stole [SOURCE]'s [ITEM]!)___",
            R"___(default.takeItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ lost\ its\ (.+?)!?)___"),
            BattleLogEventType::ITEM_TRANSFER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  [POKEMON] lost its [ITEM]!)___",
            R"___(default.removeItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ used\ its\ (.+?)!?)___"),
            BattleLogEventType::ITEM_ACTIVATED,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  ([POKEMON] used its [ITEM]!))___",
            R"___(default.activateItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ Dynamax!?)___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  ([POKEMON]'s Dynamax!))___",
            R"___(dynamax.start)___",
        });
        v.push_back({
            std::regex(R"___(Intense\ Sun)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(Intense Sun)___",
            R"___(desolateland.weatherName)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ ate\ its\ (.+?)!?)___"),
            BattleLogEventType::ITEM_ACTIVATED,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ITEM},
            R"___(  ([POKEMON] ate its [ITEM]!))___",
            R"___(default.eatItem)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ was\ hurt!?)___"),
            BattleLogEventType::DAMAGE,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(  ([POKEMON] was hurt!))___",
            R"___(default.damage)___",
        });
        v.push_back({
            std::regex(R"___(Heavy\ Rain)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(Heavy Rain)___",
            R"___(primordialsea.weatherName)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ fainted!?)___"),
            BattleLogEventType::FAINTED,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___([POKEMON] fainted!)___",
            R"___(default.faint)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ started!?)___"),
            BattleLogEventType::EFFECT_START,
            0,
            R"___()___",
            {BattleLogSlot::EFFECT},
            R"___(  ([EFFECT] started!))___",
            R"___(default.startFieldEffect)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ rose!?)___"),
            BattleLogEventType::STAT_CHANGE,
            1,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  [POKEMON]'s [STAT] rose!)___",
            R"___(default.boost)___",
        });
        v.push_back({
            std::regex(R"___((.+?)'s\ (.+?)\ fell!?)___"),
            BattleLogEventType::STAT_CHANGE,
            -1,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::STAT},
            R"___(  [POKEMON]'s [STAT] fell!)___",
            R"___(default.unboost)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ woke\ up!?)___"),
            BattleLogEventType::STATUS_HEALED,
            0,
            R"___(asleep)___",
            {BattleLogSlot::POKEMON},
            R"___(  [POKEMON] woke up!)___",
            R"___(slp.end)___",
        });
        v.push_back({
            std::regex(R"___(Sandstorm)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(Sandstorm)___",
            R"___(sandstorm.weatherName)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ used\ (.+?)!?)___"),
            BattleLogEventType::MOVE_USED,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::MOVE},
            R"___([POKEMON] used **[MOVE]**!)___",
            R"___(default.move)___",
        });
        v.push_back({
            std::regex(R"___((.+?)\ ended!?)___"),
            BattleLogEventType::EFFECT_END,
            0,
            R"___()___",
            {BattleLogSlot::EFFECT},
            R"___(  ([EFFECT] ended!))___",
            R"___(default.endFieldEffect)___",
        });
        v.push_back({
            std::regex(R"___(Go!\ (.+?)!?)___"),
            BattleLogEventType::SWITCH_IN,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON},
            R"___(Go! [FULLNAME]!)___",
            R"___(default.switchInOwn)___",
        });
        v.push_back({
            std::regex(R"___(\[(.+?)'s\ (.+?)\])___"),
            BattleLogEventType::OTHER,
            0,
            R"___()___",
            {BattleLogSlot::POKEMON, BattleLogSlot::ABILITY},
            R"___([[POKEMON]'s [ABILITY]])___",
            R"___(default.abilityActivation)___",
        });
        v.push_back({
            std::regex(R"___(Rain)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(Rain)___",
            R"___(raindance.weatherName)___",
        });
        v.push_back({
            std::regex(R"___(Hail)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(Hail)___",
            R"___(hail.weatherName)___",
        });
        v.push_back({
            std::regex(R"___(Snow)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(Snow)___",
            R"___(snowscape.weatherName)___",
        });
        v.push_back({
            std::regex(R"___(Sun)___"),
            BattleLogEventType::WEATHER,
            0,
            R"___()___",
            {},
            R"___(Sun)___",
            R"___(sunnyday.weatherName)___",
        });
        return v;
    }();
    return patterns;
}

}
}
}
