#!/usr/bin/env python3
"""
Ingest Labeled Test Images — copy from DetectorTest output into CommandLineTests.

Copies screenshots from Screenshots/labeled_tests/PokemonChampions/ (generated by
DetectorTest with "Save Labeled Test Images" enabled) into the matching
CommandLineTests/PokemonChampions/ directories for regression testing.

Usage:
  python3 tools/ingest_labeled_tests.py                     (from ColePC, default path)
  python3 tools/ingest_labeled_tests.py --from <path>       (custom source)
  python3 tools/ingest_labeled_tests.py --dry-run           (show what would be copied)
  python3 tools/ingest_labeled_tests.py --pull              (scp from ColePC first)
"""

import os
import shutil
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
DEFAULT_SRC = os.path.join(REPO_ROOT, "Screenshots", "labeled_tests", "PokemonChampions")
DEFAULT_DST = os.path.join(REPO_ROOT, "CommandLineTests", "PokemonChampions")
COLEPC_SRC = "colepc:C:/Dev/pokemon-champions/Screenshots/labeled_tests/PokemonChampions/"


def pull_from_colepc(local_dest):
    """SCP labeled tests from ColePC to local machine."""
    print(f"  Pulling from ColePC to {local_dest}...", flush=True)
    os.makedirs(local_dest, exist_ok=True)
    cmd = f'scp -r "{COLEPC_SRC}" "{os.path.dirname(local_dest)}/"'
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"  SCP failed: {result.stderr.strip()}", flush=True)
        return False
    print("  Pull OK", flush=True)
    return True


def ingest(src_root, dst_root, dry_run=False):
    """Copy labeled test images from src to dst, organized by reader."""
    if not os.path.isdir(src_root):
        print(f"Source not found: {src_root}")
        return 0

    copied = 0
    skipped = 0

    for reader_name in sorted(os.listdir(src_root)):
        src_reader = os.path.join(src_root, reader_name)
        if not os.path.isdir(src_reader):
            continue

        dst_reader = os.path.join(dst_root, reader_name)
        os.makedirs(dst_reader, exist_ok=True)

        for fname in sorted(os.listdir(src_reader)):
            if not fname.lower().endswith((".png", ".jpg")):
                continue

            src_path = os.path.join(src_reader, fname)
            dst_path = os.path.join(dst_reader, fname)

            if os.path.exists(dst_path):
                skipped += 1
                continue

            if dry_run:
                print(f"  [dry-run] {reader_name}/{fname}")
            else:
                shutil.copy2(src_path, dst_path)
                print(f"  {reader_name}/{fname}")
            copied += 1

    action = "Would copy" if dry_run else "Copied"
    print(f"\n  {action} {copied} images, skipped {skipped} duplicates")
    return copied


def main():
    args = sys.argv[1:]
    src = DEFAULT_SRC
    dry_run = False
    do_pull = False

    i = 0
    while i < len(args):
        if args[i] == "--from" and i + 1 < len(args):
            src = args[i + 1]
            i += 2
        elif args[i] == "--dry-run":
            dry_run = True
            i += 1
        elif args[i] == "--pull":
            do_pull = True
            i += 1
        elif args[i] in ("-h", "--help"):
            print(__doc__)
            sys.exit(0)
        else:
            i += 1

    if do_pull:
        pull_from_colepc(DEFAULT_SRC)

    print(f"Ingesting from: {src}")
    print(f"           to:  {DEFAULT_DST}\n")
    ingest(src, DEFAULT_DST, dry_run=dry_run)


if __name__ == "__main__":
    main()
